### ISSUE TITLE
[Not estimated yet] Architecture Research

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#1]
### As a
Developer

### I want
A better understanding of how event driven architectures are implemented best for complex event processing.
How and when to use more than one component?
What might these components do?
How would these components interact with each other?
How could new modi of transportation be added?
How could new types of input data sources be added?
What should be done within Flink what in the backend?

### Because
I want to guarantee extend-ability within the domain of multi modal transport monitoring and ETA prediction without major architecture changes

## Tasks
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
