### ISSUE TITLE
[Not estimated yet] CEP Flights Excersise with Flink: Sights and Weather

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#10]
### As a
Passenger of Lufthansa

### I want
to get informed about suitable sight seeing options at my target airport depending on the weather

### Because
I want to make the most out of my stay

## Tasks
- [ ] Pull Request open 
- [ ] subscribe to open weathermap with kafka
- [ ] use sights data to correlated with target airports from booking flights and lufthansa API
- [ ] use existing streams if applicable 
- [ ] send event with flight number city weather and suitable sight seeing option

## Acceptance Criteria
- [ ] Documented
- [ ] on CEP exercise  branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
