### ISSUE TITLE
[8] Go Microservice: Authentication

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#101]
### As a
User

### I want
to have a personalised page with only my content 

### Because
I don't want to be distracted by too much information and sort relevant infos for me

## Tasks
- [x] implement oaut2 functionality 
- [x] connect login with oauth server 
- [x] generate JWT and provide to the User
- [x] Pull Request open 

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
