### ISSUE TITLE
[20] Testing in Flink

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#102]
### As a
Developer

### I want
a stable codebase which is tested and works as expected

### Because
we all make mistakes and it will save us time later on.

## Tasks
- [ ] Pull Request open 
- [ ] evaluate what kind of useful tests there are in core and share with the team
- [ ] test Consumer Creation (outdated)

###  A 
- [ ] evaluate using database with Travis for integration test (Is it possible? Is it usable?)
- [ ] set up test database for local integration testing 
- [ ] test database methods with mocked data (no integration tests)

### B 
- [ ] unit tests for database related functions (stuck)

### C 
- [ ] test correlation function of planned and live train data (integration tests)

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by leopetter** [comment]
I wouldn't split the user stories as suggested and rather have 3-4 different people who divide the tasks between them. They should communicate and talk about best practices.

**Comment by grittaweisheit** [comment]
Documentation:
- change "TestNG Introduction" to [Testing Flink with JUnit](https://github.com/bptlab/cepta/wiki/Testing-Flink-with-JUnit)
- add [Integration Tests with Java](https://github.com/bptlab/cepta/wiki/Integration-Tests-with-Java)

**Comment by grittaweisheit** [comment]
Part B is stuck.
Mockito as well as PowerMock are not able to mock anything, because the classes can not be found.
We are thinking about dropping unit tests for database related functions
