### ISSUE TITLE
[8] User management in Frontend

### ISSUE THREAD

**Issue by grittaweisheit** [bptlab/cepta#104]
### As a

customer of cepta with several trains

### I want

to have access to my (and only my) trains with their data. And I want to be able to edit my account. 

### Because

I want so see my trains. 

## Tasks
- [x] generate a Mockup and share with the team
- [x] mock user data
- [x] create a user
- [x] edit a user
- [x] delete a user
- [x] specify a user's train id's
- [x] delete a user's train id's
- [x] overview over one user's train id's
- [x] see planned/delay table of user's trains
- [ ] Pull Request open 

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
