### ISSUE TITLE
[Not estimated yet] CEP Flights Exercise with Flink: Lounge Info

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#11]
### As a
Lufthansa passenger who booked Premium Economy or higher

### I want
to know  some details about the Lounge and the target Airport of my flight

### Because
I need to shower and use the wifi to upload the presentation for my boss

## Tasks
- [ ] Pull Request open 
- [ ] implement a feature that informs the passenger about the lounge information
- [ ] use correlated data of bookings only if premium economy or higher
- [ ] generate event for suitable passengers with loung info

## Acceptance Criteria
- [ ] Documented
- [ ] on CEP exercise branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
