### ISSUE TITLE
[5] Create complete Mockup for our Frontend

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#111]
### As a
Developer

### I want
a clear vision of how the frontend has to look like

### Because
I dont't want to frequently do style changes

## Tasks
- [ ] create different mockups of all our planned pages 
- [ ] share with the Team

## Used Tool
- figma

## Acceptance Criteria
- [ ] available in the Drive
- [ ] Reviewed by PO

**Comment by grittaweisheit** [comment]
We started here:
https://www.figma.com/file/838HkkHyiBtuNEsaXKPTZh/Untitled?node-id=0%3A1

**Comment by skydivin4ng3l** [comment]
- [ ] Admin Dashboard with all incoming events with somekind of history for all user simultaneously, group-able by user 

- [ ] User Dashboard, all incoming events, all types with some kind of history for this specific user, for all train ids

**Comment by skydivin4ng3l** [comment]
**User Dashboard:** 
Important: 
 ⁃ Trainmanagement - Delete, Edit, Create Trains
 ⁃ Overview of all possible data tables (toggle for graphs)
 ⁃ Own trains: 
     ⁃ All planed tables (searchable by id) 
     ⁃ Live train feed (all together but also searchable) 
     ⁃ Each transportation (on a specific route) with their delay history
     ⁃ Best and worst performer (trains or tracks)

Nice to have: 
 ⁃ map with all live trains


**Admin Dashboard:** 
Important: 
 ⁃ Usermanagement - Delete, Edit, Create User
 ⁃ Live train feed
 ⁃ Possibility to watch planned schedules
 ⁃ Comparison Predicted and actual live delays

Nice to have: 
 ⁃ Stats of the page (Traffic, User visits, …)
