### ISSUE TITLE
[1] Generate a detailed topic for the Bachelor thesis

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#112]
### As a
Student

### I want
to have a clear vision of my bachelor thesis

### Because
as earlier as I have that I can start wirting/working on the topic

## Tasks
- [ ] gain knowledge 
- [ ] write a headline
- [ ] write an abstract
- [ ] possible contribution that is necessary to implement in the project

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
