### ISSUE TITLE
[20] npm package for a "Path-Time-Diagram"

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#113]
### As a
User

### I want
to see  my transportations and possible ETA's in a good visualised diagram

### Because
it gives me a clear and fast overview in order to plan ahead

## Tasks
- [ ] gain knowledge about different best practices (chart.js)
- [ ] write npm package
- [ ] integration into our project
- [ ] tested

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
