### ISSUE TITLE
[8] How to properly test a go Microservice

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#114]
### As a
Developer 

### I want
a stable codebase which is tested and works as expected,
and we want to properly check whether the interfaces work as expected.

### Because
we all make mistakes and it will save us time later on.

## Tasks
- [x] look at the informations already written in the wiki page "How to build a Microservice"
- [x] research on how to perfectly test the microservice
- [x] complete the wiki page "How to build a Microservice" in the testing chapter
- [ ] spike a test case for the communication of one specific microservice (no unit tests but all other possible tests)
- [ ] share your knowledge with the team

## Acceptance Criteria
- [ ] Documented
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
Closing because there is a [basic tutorial](https://github.com/bptlab/cepta/wiki/How-to-build-a-microservice%3F) by @leopetter  and a [discussion](https://github.com/bptlab/cepta/wiki/Unit-Testing--Microservices) about testing concepts from @ma-ro in the wiki.
