### ISSUE TITLE
[8] A replayer for our weather data in go (or generally a more generic solution for all replayers)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#115]
### As a
Developer

### I want
to erase java everywhere from the project where it is not necessary and write all services in go

### Because
java and the used build tool maven is only causing headaches.
Go services and Bazel as a build tool is our new tech stack.

## Tasks
- [ ]  generalise all replayer
- [ ]  convert written java weather replayer to go
- [ ]  convert tests and you might want to write additional tests

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
