### ISSUE TITLE
[5] Write unit tests for existing go microservices

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#116]
### As a
Developer

### I want
a stable codebase which is tested and works as expected

### Because
we all make mistakes and it will save us time later on.

## Prerequisite
None

## Tasks
- [x] read the how to page
- [ ] write unit tests for the replayers (all of its replaying sources)
- [ ] write unit tests for the notification microservice
- [x] write unit tests for the authentication microservice
- [ ] write unit tests for the query microservice

## Acceptance Criteria
- [x] Documented
- [ ] on Master
- [ ] Linter is okay
- [x] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
