### ISSUE TITLE
[5] Analyse and work with our new provided data (eleta_gps)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#117]
### As a
Developer

### I want
meaningful insights in the provided data and use the data in our system

### Because
more well analysed and used data results in better ETA-Calculations for our system

## Tasks
- [x] write meta schema
- [x] check meta schema with synfioo
- [x] gain knowledge of what to do with the data
- [x] modify db-loader
- [x] load data into our database server
- [x] inform others about gained knowledge (we probably need a replayer...)

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Reviewed by PO
