### ISSUE TITLE
[3] Setup the provided VM for our database server

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#118]
### As a
Developer

### I want
to access our database from a remote server

### Because
I don't want to load all the data into my local machine

## Tasks
- [ ] get sudo rights
- [ ] run our docker environment
- [ ] load data into the database
- [ ] make it accessible for everyone

## Acceptance Criteria
- [ ] Documented
- [ ] Every team member needs to test access
- [ ] on Master
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by leopetter** [comment]
The admins forgot to give us sudo rights but they just added us to the correct group.

**Comment by romnn** [comment]
We had sudo access but then the VM became somehow unreachable from within HPI network while the admins confirmed it was running.
