### ISSUE TITLE
[3] Gain special knowledge about train delays from synfioo or other stakeholders

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#119]
### As a
Developer

### I want
more information and context about the reasons for cargo train delays

### Because
I want to gather and perfectly correlate the data I receive and predict the accurate ETA

## Tasks
- [x] Email to Susanne
- [x] Email to DB Netz
- [x] Email to Gritta`s father
- [x] Email to David Kriesel
- [ ] further Email for possible stakeholder??
- [ ] Receive additional data from Synfioo
- [ ] document received knowledge

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by leopetter** [comment]
David Kriesel darf historische Daten der Deutschen Bahn leider nicht an uns rausgeben.

**Comment by leopetter** [comment]
**Antwort der DB-Netz:** 
"Da es sich bei den Daten um interne Geschäftsdaten handelt, können wir Ihnen diese leider nicht zur Verfügung stellen."
