### ISSUE TITLE
[Not estimated yet] CEP Flights Excerise with Flink: Gate of Connection Flight

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#12]
### As a
Passenger of Lufthansa

### I want
to know what the gate and departure time for my connection flight is

### Because
I need to know where to go after landing

## Tasks
- [ ] Pull Request open 
- [ ] extend the booking mock data stream with actual possible connection flights (Lufthansa API)
- [ ] get the Departure gate and time Data (LH API)
- [ ] inform every connection flight passenger about said connection flight gate and time

## Acceptance Criteria
- [ ] Documented
- [ ] on CEP Exercise branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
