### ISSUE TITLE
[5] Go Microservice: User Management

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#120]
### As a
User

### I want
to change account details, add trains and so on

### Because
I  want to have control over my own account

## Tasks
- [x] gain knowledge about go and our other microservices
- [x] extract necessary logic from the authentication service (adding a user)
- [x] add further logic like editing, and adding of information (personal and of specific trainIDs connected to the account)
- [x] connect and update database entries with the query microservice

## Acceptance Criteria
- [x] Documented
- [x] on Dev
- [x] Linter is okay
- [x] Code Review done
- [ ] Reviewed by PO
