### ISSUE TITLE
[2] Frontend testing with Cypress??

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#121]
### As a
Developer

### I want
to have a well tested frontend

### Because
I want to avoid any bugs

## Tasks
- [ ] gain knowledge how useful it is to test which component
- [ ] document gained information 
- [ ] spike a frontend test with cypress if necessary

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
