### ISSUE TITLE
[8] Query Data from the Database and send via notification service

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#122]
### As a
User 

### I want
to receive notifications for me specifically

### Because
I need live updates for my personal trains

## Prerequisite
#96 
#97 

## Tasks
- [ ] gain knowledge about the two microservices
- [ ] establish an interface between the microservices
- [ ] query data for a specific user to send via the notification service

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO
