### ISSUE TITLE
[8] Connect Frontend (Authentication service) with Notification service

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#123]
### As a
User 

### I want
to receive notifications for me specifically

### Because
I need live updates for my personal trains

## Prerequisite
#101  
#97 

## Tasks
- [ ] gain knowledge about the two microservices
- [ ] establish an interface between the microservices
- [ ] send the generated JWT from the frontend via websocket to the notification service 
- [ ] authorise the Token in the notification websocket with generated tokens from the authentication service
- [ ] accept connection with authorised client 

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO
