### ISSUE TITLE
[5] Usage of protobuf in the frontend (build with bazel)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#129]
### As a
Developer 

### I want
to use our protobuf schemas in our frontend 

### Because
of the usage with graphql and deserializing data send via websockets

## Tasks
- [x] ask Roman about progress
- [x] find out how to compile protobuf schema to typescript
- [x] hacky but working: write simple shell script to do that while building
- [x] Merge #139 

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
@leopetter found a working approach I will implement asap

**Comment by romnn** [comment]
Turns out the @leopetter approach was missing grpc support but we do have a working solution now.

However, this story still requires #139 to be completed.

**Comment by romnn** [comment]
#139 completed.
