### ISSUE TITLE
[Not estimated yet] CEP Flights Exercise with Flink: Connection Flight can not be reached due delay

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#13]
### As a
Passenger of Lufthansa

### I want
to get informed about alternative flights if I might not get to my connection flight in time

### Because
I have to book an alternative

## Prerequisite
- [ ] #12 is done
- [ ] #8 is done  

## Tasks
- [ ] Pull Request open 
- [ ] make a prediction based on ETA and departure time of Connection flight of the passengers flight
- [ ] make a suggestion of alternative flights
- [ ] inform the passenger of the delay and necessity to book an alternative with suggestions. 

## Acceptance Criteria
- [ ] Documented
- [ ] on CEP exercise branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
