### ISSUE TITLE
[5] Protobuf Serialising/Deserialising in Flink

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#130]
### As a
Developer

### I want
one schema format (in our case protobuf)

### Because
of compatibility reasons and to avoid unnecessary code duplication

## Tasks
- [ ] talk to roman about the progress
- [ ] see the minimal working copy [here](https://github.com/romnnn/flink-kafka-protobuf)
- [ ] what is different to the setup in our dev branch and make needed changes

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
seems to be fixed already by @romnnn

**Comment by romnn** [comment]
Since #137 was merged the platform uses protobuf exclusively. 😃
