### ISSUE TITLE
[2] Replayer for GPS Container Data

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#131]
### As a
Developer

### I want
to reproduce all the data that is provided to us

### Because
we want to use the data in an event stream processing fashion

## Prerequisite
#117 
#115 

## Tasks
- [ ] gain knowledge about the other replayers (generalisation)
- [ ] change the replayer to reproduce also the newly data and send it to flink

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
