### ISSUE TITLE
[8] Receive and analyse further data sources

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#133]
### As a
Developer

### I want
more information and context about the reasons for cargo train delays (one specific use case might help)

### Because
I want to gather and perfectly correlate the data I receive and predict the accurate ETA

## Tasks
- [x] talk to Hannah Richta about possible data
- [x] talk to other people (DBNetz) to receive further data
- [x] talk to Hannah Richta about a good use case to analyze
- [x] receive information about use case and analyse all possible reasons for a delay
- [ ] develope a plan to implement the use case in our system 

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
