### ISSUE TITLE
[20] Identify and write patterns for Flink (correlate given data)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#135]
### As a
Customer

### I want
to use all my data for correlation

### Because
I need a comprehensive calculation of my ETA's

## Prerequisite
#146 

## Tasks
- [ ] Pull Request open 
- [ ] collect all needed informations from #146 
- [ ] analyse data
- [ ] identify dependencies in the data
- [ ] write patterns for calculating ETA's of this specific use case

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
