### ISSUE TITLE
[1] Add bazel to the anubis Dockerfile

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#139]
### As a
Developer

### I want
to have protobuf compiled models available in the final fe webpack build created with the `anubis/Dockerfile` container 

### Because
this is necessary for the FE to work

## Prerequisite
None

## Tasks
- [ ] Pull Request open 
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
