### ISSUE TITLE
[1] Add script for making releases

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#140]
### As a
User

### I want
a useful versioning of stable releases

### Because
this is good practice with agile development

## Tasks
- [x] Pull Request open 
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
