### ISSUE TITLE
[4] Generic high level schemas

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#143]
### As a
Developer

### I want
All our events to be conformed to one interface

### Because
this makes our platform truly independent from the underlying data

## Prerequisite
None

## Tasks
- [ ] Think about high level schemas for all transport modalities
- [ ] Adapt the replayers to conform to these schemas
- [ ] Pull Request open 
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Code Review done
- [ ] Reviewed by PO
