### ISSUE TITLE
[2] Analyse and work with our provided Data (PME)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#144]
### As a
Developer

### I want
meaningful insights in the provided data and use the data in our system

### Because
more well analysed and used data results in better ETA-Calculations for our system

## Tasks
- [x] write meta schema
- [x] check meta schema with synfioo
- [x] gain knowledge of what to do with the data
- [x] modify db-loader
- [x] load data into our database server
- [x] inform others about gained knowledge (we probably need a replayer...)

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
I started a lucid chart diagram in https://www.lucidchart.com/invitations/accept/edf07b2a-c1de-43d6-8593-06948a434813

**Comment by Quacck** [comment]
I've added a go importer in our gitlab for this
