### ISSUE TITLE
[3] Modify Replayer for all data sources

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#145]
### As a
Developer

### I want
to reproduce all the data that is provided to us

### Because
we want to use the data in an event stream processing fashion

## Prerequisite
#115   

## Tasks
- [x] gain knowledge about the other replayers (generalisation)
- [x] PME Replayer
- [x] CDIF Replayer
- [x] PlanET Replayer
- [x] ELETA Replayer
- [x] VSP Replayer

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
