### ISSUE TITLE
[2] Analyse original train data for "Red Bull" Cargo

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#146]
### As a
Developer

### I want
a specific train route route (customer)

### Because
I want a startpoint to test the correlation between all data sources

## Prerequisite
#118 

## Tasks
- [ ] Pull Request open 
- [ ] analyse the given train numbers for the "Red Bull" cargo and find the needed informations in our data

## Acceptance Criteria
- [ ] Documented
- [ ] on Dev
- [ ] Reviewed by PO
