### ISSUE TITLE
[2] Use MongoDB database for the replayer

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#149]
## Prerequisite
- [ ] #158 

## Tasks
- [x] Mongodb in dev and prod deloyment
- [ ] CSV and XML reading in Golang
- [ ] Plugins in the replayer for Postgres and Mongo Extraction
- [x] Pull Request open
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
