### ISSUE TITLE
[13] Spike csv data reader

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#15]
### As a
Developer

### I want
to import a csv Data file into kafka 

### Because
I need to generate event Data from the file

## Tasks
- [x] Pull Request open 
- [x] choose a csv file
- [x] import into DB
- [x] read from this DB into kafka
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [x] on a spike branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
```
CREATE TABLE train_sample 
(
	id integer	NOT NULL,
	referencenb integer,
	referencedeparture varchar(255),
	referenceidtime varchar(255),
	referencetimetableid integer,
	firsttimetableid integer,
	timetabledeporiid integer,
	originalstartingpointid integer,
	originalstartingpointtime varchar(255),
	originalstartingpointdelta integer,
	lasttimetableid integer,
	timetablearrterid integer,
	originaldestinationpointid integer,
	originaldestinationpointtime varchar(255),
	originaldestinationpointdelta integer,
	eurotirailid integer,
	uniqueid integer,
	timestamp varchar(255),
	servicenb integer,
	servicedeparture varchar(255),
	serviceidtime varchar(255),
	referencenboriginal integer,
	reportingim integer,
	CONSTRAINT train_sample_pkey PRIMARY KEY (id)
);
```
This did the trick for me with Postgres 12, to import the train sample data

**Comment by skydivin4ng3l** [comment]
[debezium](https://debezium.io/documentation/reference/0.10/connectors/postgresql.html) this might be usefull

**Comment by skydivin4ng3l** [comment]
I see one approach would be to let a kafka connector monitor the changes of a first empty table, which will be filled by a configurable agent, which reads row by row (ordered by timestamp) the actual filled tables and fills the monitored tables in a timebased (every so seconds) manner. So kafka will notice the changes in the tables and send out events accordingly.

**Comment by skydivin4ng3l** [comment]
[Bottled Water](https://www.confluent.io/blog/bottled-water-real-time-integration-of-postgresql-and-kafka/) puts the DB Data into an Avro Format. maybe similar to dbezium

**Comment by grittaweisheit** [comment]
The part DB to Kafka is done and documented

**Comment by skydivin4ng3l** [comment]
@grittaweisheit could you maybe add a link to the avro schema, like how to use it. 

What is the meaning of "variables". Like what does namespace mean, why do we have to include it? Is this a variable or does it just have to be included. 

Do other types exit? Are relevant for us?
Does the first "name" has to be the same name as of the table in the DB?

Is there a reference table for the conversion from Postgres types to avro types, yes? please include a link we all can use =) to have the same knowledge base.

In general more explanation or explaining links would help I think =)

**Comment by skydivin4ng3l** [comment]
how and when does the avro class get generated? what commands have to be used? can i change the avro and regenerate? do i have to delete it first?

**Comment by skydivin4ng3l** [comment]
does the code below "Generate Java class" has to be included in the maven file? please try to be as specific as possible =)

**Comment by skydivin4ng3l** [comment]
the beware part should maybe above the "Generate Java class" topic cause it belongs to the avro schema?

**Comment by skydivin4ng3l** [comment]
For readability the information about customization of connect() and fetchdatanext() it would be good to provided this information at the vicinity of the code fragment.

additionally to row information e.g. at serializer maybe include the code line, since we do not have row information provided.

**Comment by skydivin4ng3l** [comment]
I like to see magic, but since it is a open source project and we have connections to a professional business partner, I would prefer a more professional approach concerning the actual guideline for execution.

**Comment by skydivin4ng3l** [comment]
we all need access to the loader, and the Documentation should be available from our wiki at least with a link to the readme. 

- [ ] docker command line param for exec like the python command
- [ ] explanation for usage of volumes for import folder

on windows:
C:\Studium\BP\Repo\CSVLoader\db-loader>docker run --network="host" -v c:/Studium/BP/TrainData/import:/import postgreloader /import                                                                               Postgres is up - executing command                                                                                                                                                                               /usr/local/lib/python3.7/runpy.py:125: RuntimeWarning: 'postgreloader.load' found in sys.modules after import of package 'postgreloader', but prior to execution of 'postgreloader.load'; this may result in unpredictable behaviour                                                                                                                                                                                                warn(RuntimeWarning(msg))                                                                                                                                                                                      INFO:loader:No files to unzip                                                                                                                                                                                    WARNING:loader:Queue is empty (received timeout)                                                                                                                                                                 ERROR:loader:Executing hooks/functions.sql errored with hooks/functions.sql: No such file or directory

**Comment by skydivin4ng3l** [comment]
would we like to add the transfer to the new schema within this story or should the transfer a new story?

**Comment by romnn** [comment]
The csv reader is done and documented. See [code and documentation](https://github.com/romnnn/postgresimporter) and the [internal repository](https://gitlab.hpi.de/cepta/bp-data-helper) for BP members. This will also be mentioned in the merge for #37 and #43 respectively.

**Comment by romnn** [comment]
> would we like to add the transfer to the new schema within this story or should the transfer a new story?

The transfer was completed with #58 and has already been merged into master.
