### ISSUE TITLE
[2]  Analyse and work with our provided Data (PLANET)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#155]
### As a
Developer

### I want
meaningful insights in the provided data and use the data in our system

### Because
more well analysed and used data results in better ETA-Calculations for our system

## Tasks
- [x] write meta schema
- [x] check meta schema with synfioo
- [ ] gain knowledge of what to do with the data
- [ ] modify db-loader
- [ ] load data into our database server
- [ ] inform others about gained knowledge (we probably need a replayer...)

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Reviewed by PO

**Comment by leopetter** [comment]
https://www.lucidchart.com/invitations/accept/edf07b2a-c1de-43d6-8593-06948a434813
