### ISSUE TITLE
[2] Research how to save correlation related Data, how does flink save data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#16]
### As a
Developer

### I want
to save and access correlation related Data - like planned train schedule Event data

### Because
 I want to correlate them with (when) train related live events occur.

## Tasks
- [ ] Research how flink saves Data
- [ ] Decide if this method is useful for us
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
Rocks DB extern oder In Memory

**Comment by skydivin4ng3l** [comment]
#21 if DB is not suitable

**Comment by Quacck** [comment]
I've added a couple thought [here](https://github.com/bptlab/cepta/wiki/Research-how-to-save-correlation-related-Data,-how-does-flink-save-data%3F), in summary; Flink's internal data is probably not the right approach as it doesn't really allow saving relational data.

**Comment by skydivin4ng3l** [comment]
concerning your findings, can you provide links for further reading, e.g. where you got your information from? Please =)

**Comment by skydivin4ng3l** [comment]
please rephrase in a semi serious way, no "bums" and "fancyschmancies" please, this is a open source project and is build to be continued in the future and the content may be read by others. so to make a good impression also towards our project partners.

**Comment by Quacck** [comment]
Alrighty, i have translated the wiki page to english and made it a bit more serious :)

**Comment by skydivin4ng3l** [comment]
sorry but i would liked to see a link to read further about your findings of the internal state information you gathered. Then it is fine =) Thank you.
