### ISSUE TITLE
[3] Create Schema with important attributes for VSP Data and load into database

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#160]
### As a
Developer

### I want
meaningful insights in the provided data and use the data in our system

### Because
more well analysed and used data results in better ETA-Calculations for our system

## Tasks

We don't need a meta schema but we propably don't need all the provided attributes. Analyse the data and prepare the data for loading it into the database.
- [x] analyse needed schema
- [ ] gain knowledge of what to do with the data
- [x] modify db-loader
- [x] load data into our database server
- [ ] inform others about gained knowledge

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
I added my analysis in our gitlab.

**Comment by Quacck** [comment]
One thing we could do is correlate the delays on a per-station basis, e.g. building work would cause delays to other trains. Also we could try finding patterns after which follow-up trains would get delayed.
