### ISSUE TITLE
[3] Analyse reasons for delays with the VSP Data and compare to DB Cargo results

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#161]
### As a
Developer

### I want
to know what data I can trust

### Because
I don't want to work with wrong statements resulting from wrong data

## Prerequisite
#160 

## Tasks
Pull Request not needed because it doesn't belong on the master
- [ ] analyse reasons for a delay in the vsp data
- [ ] collect results from all month 
- [ ] compare different results
- [ ] compare to DB Cargo
- [ ] write tests for flink with the gained knowledge (test the correlation and made predictions)

## Acceptance Criteria
- [ ] Documented
- [ ] Code Review done
- [ ] Reviewed by PO
