### ISSUE TITLE
[8] Correlate Delays VSP and PME

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#163]
### As a
Developer

### I want
to know which data sources I can trust and which data comes from where

### Because
we dont't want to work with the wrong data.

## Prerequisite
#157 

## Tasks
- [ ] correlate VSP and PME data
- [ ] analyse whether they include the same data (delay information)
- [ ] share knowledge with the team
- [ ] share knowledge with Synfioo

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
