### ISSUE TITLE
[4] Mongoimporter for XML-Data

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#164]
### As a
Developer

### I want
to import xml files into the used database (mongoDB)

### Because
we were provided with data as xml files from synfioo

## Tasks
- [x] Extend the mongoimporter in gitlab for xml data
- [x] handle thousand of small files

## Acceptance Criteria
- [ ] Documented 
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO
