### ISSUE TITLE
[1] Mongoimporter for JSON data

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#165]
### As a
Developer

### I want
to import json files into the used database (mongoDB)

### Because
we might have data sources that provide JSON data in the future (ex. weather data)

## Tasks
- [ ] Extend the mongoimporter in gitlab for json data

## Acceptance Criteria
- [ ] Documented 
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO
