### ISSUE TITLE
[5] Dump all the data in the mongoDB

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#166]
### As a
Developer

### I want
to work with the data in a database

### Because
I want specific queries and I want to replay the data

## Prerequisite
#144 #155 #134 #117

## Tasks
- [x] load PME data into DB
- [ ] load PlanET data into DB
- [x] load VSP data into DB
- [ ] load CDIF data into DB
- [x] loader for ELETA data for MongoDB
- [x] load ELETA data into DB
- [ ] load Eleta_gps data into DB
- [x] load DarkSky data into DB
- [x] check the data capacity of the VM

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
Mongo DB loader for ELETA is finshed
https://gitlab.hpi.de/cepta/eleta/merge_requests/1

**Comment by Quacck** [comment]
I am not really sure how the import paths in the delay_explanation loader need to be written. Does anyone mind helping me there?
