### ISSUE TITLE
[1]  Export eleta_gps data as CSV from MongoDB

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#167]
### As a
Developer

### I want
to see my data even when I don't have DB access or when I am home

### Because
this makes the data accessible and I can work remotely

## Prerequisite
#166
#164

## Tasks
- [x] analyse how to export the data (per day, month, trainID....)
- [x] export data as csv
- [x] import csv files into our GitLab

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by romnn** [comment]
We chose to export the table as a JSON file due to better support with MongoDB
