### ISSUE TITLE
[2] Spike Kafka to Flink

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#17]
### As a
Developer

### I want
subscribe to a kafka topic and read data

### Because
I want to use the Data provided

## Tasks
- [ ] Pull Request open 
- [x] subscribe to kafka topic
- [x] printout on console of data from kafka
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on spike branch
- [x] verify configuration works as intended
- [ ] Code Review done
- [x] Reviewed by PO
