### ISSUE TITLE
[3] Search for all informations for "Red Bull Cargo" in ELETA Data

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#170]
### As a
Developer

### I want
to test all assumptions on one specific Use-case

### Because
we need a starting point

## Prerequisite
#166 

## Tasks
- [x] find all the data associated to the Red Bull Cargo (Tip: use country and train ID primarily and you might have to join other collections to receive the necessary informations)
- [ ] analyse the collected data for possible delays (Can you already see a delay in the timestamps? What is the reason for this delay?)
- [ ] Documentation:
  - [ ] helpful queries to find data
  - [ ] all the information collected during the process (What was challenging? What was helpful?)
- [ ] save possible data entries as samples in a different collection
- [ ] possible patterns we can use in Flink?
- [ ] write tests for flink with the gained knowledge (test the correlation and made predictions)

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
https://github.com/bptlab/cepta/wiki/Redbull-in-our-Traindata I've started documenting in this wiki entry.
