### ISSUE TITLE
[2] Search for all information for "Red Bull Cargo" in PlanET

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#171]
### As a
Developer

### I want
to test all assumptions on one specific Use-case

### Because
we need a starting point

## Prerequisite
#166 

## Tasks
- [x] find all the data associated to the Red Bull Cargo (Tip: use country and train ID primarily and you might have to join other collections to receive the necessary informations)
- [ ] analyse the collected data for possible delays (Can you already see a delay in the timestamps? What is the reason for this delay?)
- [ ] Documentation:
  - [ ] helpful queries to find data
  - [ ] all the information collected during the process (What was challenging? What was helpful?)
- [ ] save possible data entries as samples in a different collection
- [ ] possible patterns we can use in Flink?
- [ ] write tests for flink with the gained knowledge (test the correlation and made predictions)

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
