### ISSUE TITLE
[2] Search for all information for "Red Bull Cargo" in CDIF

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#172]
### As a
Developer

### I want
to test all assumptions on one specific Use-case

### Because
we need a starting point

## Prerequisite
#166 

## Tasks
- [ ] find all the data associated to the Red Bull Cargo (Tip: use country and train ID primarily and you might have to join other collections to receive the necessary informations)
- [ ] analyse the collected data for possible delays (Can you already see a delay in the timestamps? What is the reason for this delay?)
- [ ] Documentation:
  - [ ] helpful queries to find data
  - [ ] all the information collected during the process (What was challenging? What was helpful?)
- [ ] save possible data entries as samples in a different collection
- [ ] possible patterns we can use in Flink?
- [ ] write tests for flink with the gained knowledge (test the correlation and made predictions)

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
### Mögliche Replay Attribute
Es gibt zwei mögliche Szenarien:
1. Replay nach Abzugsdatum
d.h. wir simulieren den wahrscheintlich einizgen zur Zeit mögliche Kommunikation mit dem Bereitsteller der Daten vermutlich der Bahn.
**Mögliches Problem:** Daten werden aktualisiert, d.h. unterschiedliche Informationen über das selbe Ereignis werden mehrfach gesendet, aber chronologisch das aktuelleste zuletzt.

2. Replay nach PlanDate und EventArrival/DepatureTime was dem tatsächlichen Eventprozessing am nähesten kommt, da dann wenn die Events eintreten die Daten gesendet werden.
d.h. jede Zeile wird mindestens drei mal gesendet möglicherweise unvollständig zu erst planDate d.h. mit PlannedArrival/DepartureTime und dann jeweils zu den Zeitpunkten von eventArrival/DepatureTime.
**Mögliches Problem:** Selbes Problem wie bei 1. ABER man könnte entsprechende "Event" Zeilen nur von dem aktuellsten Abzugsdatum replayen.

#### Interessante Attribute und Attributwerte
Zugnummer mit serviceCode_addition: 
- leer => Zugfahrt, ein Tfz an der Spitze (nur ein Tfz im Zugverband)
- L0 beginnend => Leerfahrt
- NX => Zuglok vorn mit Zwangsbindung
- I beginnend => Instandhaltung

Beiden mit Event- beginnenden Timestamps sind oft leer, wenn es zu ausfällen oder zb es sich um rangieren handelt hier werden keine Ist-Zeiten erfasst. Um die reinen Daten zu replayen ist also nach der existenz solcher Einträge zu filtern.

#### Probleme
Der selbe Zug also komplette Eintrag kann öfter vorkommen UND es kann auch vorkommen, dass sich diese Mehrfacheinträg in ihrer Eventzeit unterscheiden. Das mag an Updates liegen, da die Daten immer nur Tage weise in den csv liegen und an folgenden Abzügen aktualisierte Daten vorliegen, bisher lassen wir das Abzugsdatum weg beim parsen in die Datenbank, was zu diesem Problem führt.

### Hilfreiche Querie
```
db.getCollection('locomotive').find(
{
$and:[{
    $or : [
           {serviceCode:"49054"}, {serviceCode:"49050"}, {serviceCode:"49051"}, {serviceCode:"49052"}, {serviceCode:"49053"}, {serviceCode:"49054"}, {serviceCode:"49055"}, {serviceCode:"49056"}, {serviceCode:"49057"}, {serviceCode:"49058"}, {serviceCode:"49059"}, {serviceCode:"49060"},
           {serviceCode:"49061"}, {serviceCode:"49062"}, {serviceCode:"49063"}, {serviceCode:"49064"}, {serviceCode:"49066"},// {serviceCode:"60055"}, {serviceCode:"60065"}, {serviceCode:"60067"}, {serviceCode:"60076"}, {serviceCode:"60486"}, {serviceCode:"60487"}, {serviceCode:"60489"}
    ]},
    //{$or:[{startStation:"XSBU"},{startStation:"KG  C"}]},
    //{planId: "UC24186"},
    //{"plannedDepartureTime": { "$eq": ISODate("2019-01-09 09:18:00.000+02:00")}},
    {eventDepartureTime: {$exists: true}}
]}).sort({plannedDepartureTime:1})
```
#### Beispielzug für Redbull

von Buch (XSBU) in der Schweiz nach Kirchweyhe (HKI) bei Bremen hin und zurück.
Hin: TrainId: 49060 - 6min früher als geplant gestartet und 2h 31min (151min) später als geplant angekommen
```
{
    "_id" : ObjectId("5e8cdd11a96b78b69f784790"),
    "vehicleId" : "91806185109-6",
    "planId" : "WCTR185",
    "planDate" : NumberLong(2),
    "serviceBlockNumber" : NumberLong(1),
    "plannedDepartureDate" : ISODate("2019-01-03T01:00:00.000+02:00"),
    "intermediateStations" : NumberLong(6),
    "serviceCodeAddition" : "",
    "serviceCode" : "49060",
    "plannedDepartureTime" : ISODate("2019-01-03T02:00:00.000+02:00"),
    "eventDepartureTime" : ISODate("2019-01-03T01:54:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2019-01-03T19:48:00.000+02:00"),
    "eventArrivalTime" : ISODate("2019-01-03T22:19:00.000+02:00"),
    "endStation" : "HKI",
    "startStation" : "XSBU",
    "trackLength" : NumberLong(1097),
    "nextPlanId" : "JCKS185",
    "maxSpeed" : NumberLong(100)
}
```
Zurück: TrainId: 49051 - 47min früher als geplant gestartet und 60min später als geplant angekommen
```
{
    "_id" : ObjectId("5e8c9993a96b78b69f00161c"),
    "vehicleId" : "91806185100-5",
    "planId" : "WCTR185",
    "planDate" : NumberLong(3),
    "serviceBlockNumber" : NumberLong(2),
    "plannedDepartureDate" : ISODate("2019-01-11T01:00:00.000+02:00"),
    "intermediateStations" : NumberLong(2),
    "serviceCodeAddition" : "",
    "serviceCode" : "49051",
    "plannedDepartureTime" : ISODate("2019-01-11T04:21:00.000+02:00"),
    "eventDepartureTime" : ISODate("2019-01-11T03:43:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2019-01-12T00:26:00.000+02:00"),
    "eventArrivalTime" : ISODate("2019-01-12T01:26:00.000+02:00"),
    "endStation" : "XSBU",
    "startStation" : "HKI",
    "trackLength" : NumberLong(1097),
    "nextPlanId" : "WCTR185",
    "maxSpeed" : NumberLong(100)
}
```
#### VehicleId
VehicleIds scheinen nicht durchgängig dokumentiert, also die Bewegungen dieser Lok.

Betrachtung von Lok: 91806185109-6 lückenlos sortiert per PlannedDeparturTime

Zunächst fährt diese Lok am 2018-12-31 eine Leerfahrt mit der TrainId 49054 von Buch in der Schweiz (XSBU) nach (XSBR)  (IST Zeiten werden bei Leerfahrten nicht erfasst)
```
{
    "_id" : ObjectId("5e8cdd0ba96b78b69f780b2b"),
    "vehicleId" : "91806185109-6",
    "planId" : "WCTR185",
    "planDate" : NumberLong(3),
    "serviceBlockNumber" : NumberLong(1),
    "intermediateStations" : NumberLong(-9223372036854775808),
    "serviceCodeAddition" : "L0",
    "serviceCode" : "49054",
    "plannedDepartureTime" : ISODate("2018-12-31T09:18:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2018-12-31T12:41:00.000+02:00"),
    "endStation" : "XSBR",
    "startStation" : "XSBU",
    "trackLength" : NumberLong(192),
    "nextPlanId" : "WCTR185",
    "maxSpeed" : NumberLong(0)
}
```
Dann wieder eine Leerfahrt am 2019-01-02 zurück mit der TrainId 49051 nach Buch in der Schweiz (XSBU) von (XSBR) aus
```
{
    "_id" : ObjectId("5e8c99aaa96b78b69f01acd0"),
    "vehicleId" : "91806185109-6",
    "planId" : "WCTR185",
    "planDate" : NumberLong(1),
    "serviceBlockNumber" : NumberLong(1),
    "intermediateStations" : NumberLong(-9223372036854775808),
    "serviceCodeAddition" : "L0",
    "serviceCode" : "49051",
    "plannedDepartureTime" : ISODate("2019-01-02T20:57:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2019-01-03T00:26:00.000+02:00"),
    "endStation" : "XSBU",
    "startStation" : "XSBR",
    "trackLength" : NumberLong(192),
    "nextPlanId" : "WCTR185",
    "maxSpeed" : NumberLong(0)
}
```

Eine der ersten Fahrten mit IST-Zeit ist mit der TrainId: 49060 am 2019-01-03, von Buch (XSBU) nach Kirchweyhe (HKI) bei Bremen
```
{
    "_id" : ObjectId("5e8cdd11a96b78b69f784790"),
    "vehicleId" : "91806185109-6",
    "planId" : "WCTR185",
    "planDate" : NumberLong(2),
    "serviceBlockNumber" : NumberLong(1),
    "plannedDepartureDate" : ISODate("2019-01-03T01:00:00.000+02:00"),
    "intermediateStations" : NumberLong(6),
    "serviceCodeAddition" : "",
    "serviceCode" : "49060",
    "plannedDepartureTime" : ISODate("2019-01-03T02:00:00.000+02:00"),
    "eventDepartureTime" : ISODate("2019-01-03T01:54:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2019-01-03T19:48:00.000+02:00"),
    "eventArrivalTime" : ISODate("2019-01-03T22:19:00.000+02:00"),
    "endStation" : "HKI",
    "startStation" : "XSBU",
    "trackLength" : NumberLong(1097),
    "nextPlanId" : "JCKS185",
    "maxSpeed" : NumberLong(100)
}
```
Nun ist jedoch die direkt darauffolgende Aufzeichnung dieser Lok am 2019-01-07 und zwar von OFFENBURG GBF A (ROG A) nach WANNE-E BRO (EWANB).
Wie die Lok von Kirchweyhe (HKI) nach OFFENBURG GBF A (ROG A) kam ist unbekannt.
```
{
    "_id" : ObjectId("5e8c99c0a96b78b69f025955"),
    "vehicleId" : "91806185109-6",
    "planId" : "WCTR185",
    "planDate" : NumberLong(1),
    "serviceBlockNumber" : NumberLong(2),
    "plannedDepartureDate" : ISODate("2019-01-07T01:00:00.000+02:00"),
    "intermediateStations" : NumberLong(3),
    "serviceCodeAddition" : "",
    "serviceCode" : "49055",
    "plannedDepartureTime" : ISODate("2019-01-07T16:28:00.000+02:00"),
    "eventDepartureTime" : ISODate("2019-01-07T16:32:00.000+02:00"),
    "plannedArrivalTime" : ISODate("2019-01-08T01:08:00.000+02:00"),
    "eventArrivalTime" : ISODate("2019-01-08T00:27:00.000+02:00"),
    "endStation" : "ROG A",
    "startStation" : "EWANB",
    "trackLength" : NumberLong(489),
    "nextPlanId" : "WCTR185",
    "maxSpeed" : NumberLong(100)
}
```

#### Stationsclean für Redbull Start

Buchs (SG) existiert aber bei StationAbbreviation ist der Wert Null

```
{
    "_id" : ObjectId("5e8d024da96b78b69f840a7d"),
    "stationName" : "\nBUCHS (SG)",
    "stationNameSeqNr" : NumberLong(2),
    "stationAbbreviation" : "NULL",
    "stationCode" : NumberLong(85094045),
    "countryId" : NumberLong(85),
    "validStartDate" : ISODate("2012-11-09T01:00:00.000+02:00"),
    "latitude" : 47.16841,
    "longitude" : 9.47863,
    "stationType" : "BF"
}
```
Allerdings gibt es auch noch andere Einträge
```
{
    "_id" : ObjectId("5e8d024da96b78b69f840a7e"),
    "stationName" : "\nBUCHS (SG)",
    "stationNameSeqNr" : NumberLong(1),
    "stationAbbreviation" : "NULL",
    "stationCode" : NumberLong(-9223372036854775808),
    "countryId" : NumberLong(81),
    "validStartDate" : ISODate("2017-03-27T00:00:00.000+02:00"),
    "latitude" : 1.79769313486232e+308,
    "longitude" : 1.79769313486232e+308,
    "stationType" : "BF"
}


{
    "_id" : ObjectId("5e8d024da96b78b69f840a7f"),
    "stationName" : "\nBUCHS (SG)",
    "stationNameSeqNr" : NumberLong(3),
    "stationAbbreviation" : "NULL",
    "stationCode" : NumberLong(-9223372036854775808),
    "countryId" : NumberLong(85),
    "validStartDate" : ISODate("2013-08-16T00:00:00.000+02:00"),
    "latitude" : 1.79769313486232e+308,
    "longitude" : 1.79769313486232e+308,
    "stationType" : "Gp"
}

{
    "_id" : ObjectId("5e8d024da96b78b69f840a80"),
    "stationName" : "\nBUCHS (SG) CT",
    "stationNameSeqNr" : NumberLong(1),
    "stationAbbreviation" : "NULL",
    "stationCode" : NumberLong(-9223372036854775808),
    "countryId" : NumberLong(-9223372036854775808),
    "validStartDate" : ISODate("2006-12-20T01:00:00.000+02:00"),
    "validEndDate" : ISODate("2007-01-01T01:00:00.000+02:00"),
    "latitude" : 1.79769313486232e+308,
    "longitude" : 1.79769313486232e+308,
    "stationType" : "NULL"
}
```

#### Stations Allgemein

Strings sollten beim neuladen gecleaned werden also Spaces und /n getrimt werden. *DONE*
