### ISSUE TITLE
[Not estimated yet] Research Pipeline Tech Limitations [Unclear if necessary now]

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#18]
### As a
Developer

### I want
to find out: 
- What are the Main Challenges processing Data with kafka and flink
- What might change if scope gets bigger?

### Because
I need confidence with our tech

## Tasks

- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by romnn** [comment]
Closing as not necessary.
