### ISSUE TITLE
[5] Configure Travis to run our local Tests

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#19]
### As a
Developer

### I want
a working CI environment, which runs all tests

### Because
to improve overall product quality

## Tasks
- [x] Pull Request open
- [x] write a test which can fail 
- [x] Travis runs all tests
- [x] provide a test case which tests travis failure detection
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on all branches
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
