### ISSUE TITLE
[3] Review Frontend Mockup 

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#190]
### As a
Developer

### I want
to finalise the wanted look for the frontend

### Because
I want to start implementing this design and not tweek it in the process

## Tasks
- [x] self analyze what can be done better
- [x] discuss in the team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO
