### ISSUE TITLE
[4] Refactor Frontend 

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#192]
### As a
User

### I want
a beautiful and usable UI

### Because
I want to find and access all the provided data as quick as possible

## Tasks
- [x] Pull Request open 
- [x] implement mockups into anubis (mock data)

## Acceptance Criteria
- [x] on Dev
- [x] Linter is okay
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Looks good! The dashboard and trainmanagement looks kinda messed up but we can surely avoid showing that in the upcoming presentation :D

**Comment by leopetter** [comment]
I guess we can. We saw that it breaks on really big screen and we will fix this in the next iteration when we connect the data to the frontend.
