### ISSUE TITLE
[Not estimated yet] Basic Architecture Spike 1

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#2]
### As a
Developer

### I want
to gain experience by implementing a small spike with basic pipeline Kafka -> Flink CEP plugin -> any consumer e.g kafka for the correlated Result event on a console output.
What possibilities to achieve this are there?
What are the Main Challenges?
What might change if the scope get bigger?

### Because
I want to get a deeper understanding of how to implement all relevant components needed to correlate event data with route information

## Tasks
- [ ] Pull Request open
- [ ] gain knowledge
- [ ] prepare presentation with your insights for the team

## Acceptance Criteria
- [ ] Documented
- [ ] on Spike Branch
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
CEP Example might me useful start for this. #8

**Comment by romnn** [comment]
Closing because of limited time
