### ISSUE TITLE
[5] Decide about Prototype Use case

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#20]
### As a
Team of Developers

### We want
to exactly know what our goal is for the Prototype

### Because
we need a shared vision

## Tasks
- [x] Decide what our goal is
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO
