### ISSUE TITLE
[5] Unifying all schemas and last preparation before loading

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#203]
### As a
Database Admin

### I want
a unified naming across all collections for the same field

### Because
this results in less confusion and simpler correlation

## Tasks
- [x] Pull Request open 
- [x] gain knowledge about different fields
- [x] create unified naming
- [x] refactor the proto files and schemas

## Acceptance Criteria
- [x] Documented
- [ ] on Master
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
