### ISSUE TITLE
[4] Remove duplicates from incoming events

### ISSUE THREAD

**Issue by grittaweisheit** [bptlab/cepta#204]
### As a 
Flink developer using the incoming events in patterns

### I want
to have streams without duplicates

### Because
they make pattern implementations harder and are unnecessary and bothersome 

## Tasks
- [x] Pull Request open 
- [x] remove duplicates (either in the replayer or with a Flink method)
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [ ] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
I feel like we should test wether this removes non-duplicates.
Like testing wether the stream(1,2,3) gets reduced to a stream(1,2,3). --> Sure thing :)

**Comment by Quacck** [comment]
Is there a way to test the function on any event type we have without too much effort? --> NO

**Comment by Quacck** [comment]
When looking at code quality, I have a few observations:
The two tests use different names for essentially the same things; one test has `eliminationStream` and the other has `duplicateFreeStream`. Same with `duplicateFreeData` and `removedInteger` (which actually are the remaining integers?)

We could also count the elements with a specific value and assertEquals() that value, instead of using mildly confusing flags to count.

--> Done :)

**Comment by Quacck** [comment]
Do you think there is a more descriptive name for the CustomCountTrigger? --> NO
