### ISSUE TITLE
[2] Find a better DB for usage with Flink following #16

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#21]
### As a
Developer

### I want
to save and access correlation related data with a non flink interal DB

### Because
flinks own DB is not suitable for our usecase

## Tasks
- [ ] Set up a Database for usage with Flink
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on spike branch
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
I've added my code in https://github.com/bptlab/cepta/tree/21-db-for-flink

**Comment by skydivin4ng3l** [comment]
this misses any kind of documentation.
Which DB is used?
Why was this DB chosen?
What does this spike do exactly?
How to use this spike?

**Comment by Quacck** [comment]
I tried to answer your questions in the wikipage.

**Comment by skydivin4ng3l** [comment]
Please take a look at the wiki page, I made some comprehensibility and readability changes, to try to give you a better understanding what I expected.

please add the missing information written in Uppercase. Thank you!
