### ISSUE TITLE
[4] Single command k8s helm chart

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#210]
### As a
customer/administrator

### I want
to be able to install a production ready deployment with a single command into an existing kubernetes cluster

### Because
this will integrate with existing system deployments and provide best-in-class scalability.

## Prerequisites
- [x] #211 

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Add extensive and good deployment documentation

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
