### ISSUE TITLE
[1] Packaging anubis to docker hub as part of the release workflow

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#211]
### As a
Maintainer

### I want
to publish anubis images to docker hub

### Because
this will enable fast deployments

## Prerequisites
None

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Update `ci/release.sh` to build, tag and publish anubis

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
