### ISSUE TITLE
[2] Stabilize microservice startup

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#214]
### As a
End user

### I want
all microservices to reliably perform initialization and startup procedures without eager exiting during temporary resource unavailabilites

### Because
this allows for deterministic and reliable system starts

## Prerequisites
None

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Implement busy wait or exponential backoff
- [ ] Allow for custom timeout and max attempts
- [ ] Validate with empirical starts of the dev deployment
- [ ] Debug an inf loop condition of all golang services with graceful shutdown

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
