### ISSUE TITLE
[1] Conform bazel targets

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#216]
### As a
Developer

### I want
a consistent naming of bazel targets

### Because
it's nice

## Prerequisites
None

## Tasks
- [x] Open Pull Request
- [x] Gain knowledge about different best practices
- [x] Prepare a short presentation to share your insights with the Team
- [x] Consistent naming of bazel targets

## Acceptance Criteria
- [x] Documented
- [x] Merged in master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
