### ISSUE TITLE
[2] Generic and internal models

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#218]
### As a
Developer

### I want
to be able to enforce strong model type guarantees for the front and backend services and exchange internal data via protobuf schemas

## Prerequisites
None

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Implement generic wrapper schemas
- [ ] Implement internal models for the #192 frontend 
- [ ] Think about a good hashing / checksum mechanism for protobuf

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
