### ISSUE TITLE
[13] Spike API to Kafka (e.g. Weather)

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#22]
### As a
Developer

### I want
To get periodical Data from a API provider like dark sky

### Because
we need a data source

## Tasks
- [x] write / use a kafka connector or something applicable
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO
