### ISSUE TITLE
Correlate & enrich input events within Flink 

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#221]
### As a

Train analyzer

### I want

to correlate all data we get to a specific train. That means enriching the planned data with e.g. crew activities, checkpoints, locomotive.

We could also enrich the live data with the actually occurring events. Like the reasons for delays.

Please try to think about different approaches. We could for example do it on a station-basis (there are ... planned events here, with the following activities happening), create planned events with additional information, or completely new events.

### Because

manually finding patterns is very hard. Having the data aggregation done by a machine would allow us to better see patterns in our data. 

## Tasks
- [ ] Open Pull Request
- [ ] replay all data in flink
- [ ] enrich the planned and live events with more information
	- [ ] locomotive
	- [ ] crew
	- [ ] weather
	- [ ] checkpoints
	- [ ] delay_explanation

## Acceptance Criteria
- [ ] Documented, how did we correlate the different events (maybe in the ER-diagramm)
- [ ] Merged in master if possible, but feel free to spike your ideas first.
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
Is this story even relevant anymore or should these enrichments be made within patterns?
