### ISSUE TITLE
Simulate Live-Operation in Replayer

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#222]
### As an

Event

### I want

to be replayed in a similar fashion as I would appear in the real world.

### Because

that way we can simulate how our system would work without the database and with real data.

It would also help our project partner if we worked with similar conditions.

## Tasks
- [ ] discuss with the team on how we should replay different data 
- [ ] change replayers accordingly

## Acceptance Criteria
- [ ] Documented
- [x] Merged in dev
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
As far as I can see you changed the sorting for the livetrain but not for our other datasets. 
A major part of this story would be to replay the locomotive events in a sensible way: being able to replay the incoming (planned) locomotives and some kind of update when they actually happen, if not more.
