### ISSUE TITLE
Create an outline for the technical presentation

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#223]
### As a

presenter

### I want

to know which topics in the technical presentation we cover.

### Because

we we need to research those topics. Maybe we can also get early feedback from our academic advisors.

## Tasks
- [x] talk with the team which topics we deem important
- [x] document the outline
- [x] get feedback 

## Acceptance Criteria
- [x] Documented
- [x] Good feedback
- [ ] Tests are written and green?
- [x] Reviewed by PO
