### ISSUE TITLE
Prepare Technical Presentation

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#225]
### As a

project team

### We have

to give the 🪑 insight into our project implementations.

### Because

we can get feedback and inspiration :)

## Prerequisites

#223, #224 

## Tasks
- [x] check with team on the deadlines
- [x] document details of the presentation (e.g. when? webcam? length? audience? screen-share?)
- [x] summarize and research the topics from our outline, split the responsibilities
- [ ] create a neat presentation, link in comments
- [x] get feedback from our advisors
- [ ] practice the presentation
- [ ] ... infront of the team!

## Deadlines

16.04, finish (broad) outline, decide on presenters
24.04, finish the slides
28.04 11:00, give Presentation for the team
30.04 13:30-14:30, technical Presentation
