### ISSUE TITLE
GRPC Interface for the replayer

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#226]
### As a
Developer

### I want
my internal tests to be able to access the replayer for my tests via a well defined grpc interface

## Prerequisites
None

## Tasks
- [x] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Add grpc interface to the replayer
- [ ] Use in at least one integration test

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
I assume the PR for this story was [this one](https://github.com/bptlab/cepta/pull/230)?
This did not have a code review as far as I can see; also our CI failed but was still merged.

Please add some documentation or share with us how these replayers will now be used for tests or where your documented example is located at.
