### ISSUE TITLE
Analyse the Wagon Train Run Data 

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#227]
### As a
Developer

### I want
meaningful insights in the provided data and use the data in our system

### Because
more well analysed and used data results in better ETA-Calculations for our system

## Tasks
- [x] write meta schema
- [x] check meta schema with synfioo
- [ ] gain knowledge of what to do with the data
- [x] modify db-loader
- [x] load data into our database server
- [x] inform others about gained knowledge (we probably need a replayer...)

## Acceptance Criteria
- [x] Documented
- [ ] on Master
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Look great so far, but do you mind updating our documentation? Like adding the schema to our gitlab and updating the glossary and maybe adding it to the ER diagramm.

**Comment by leopetter** [comment]
Yes of course, I totally forgot. I have updated the meta-shemas, the gloassary, the isr repo and our "ER-diagramm".
