### ISSUE TITLE
Calculate and monitor average transport speed 

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#229]
### As a
Train Operator

### I want
to be able to track the average speed of any transport vehicles and receive notifications when the average speed decreases unexpectedly

### Because
then i can initiate mitigation

## Prerequisites
- [x] #218
- [x] #226 
- [x] #192 

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
