### ISSUE TITLE
[13] TestNG (with Flink) Introduction for the Team

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#23]
### As a
Developer

### I want
to know how tests with testng have to be written.

### Because
I need some guidelines and a general overview about testNG and how it interacts with flink/Kafka including some examples in varying complexity

## Tasks
- [x] Pull Request open 
- [x] Add some example Tests as best practices in different complexity
- [x] ..including mocking events for flink
- [x] suggest how and what should be tested in relation to flink, we don't want to test flink itself but our code, but how exactly?
- [x] tests for accessing the DB for Planned data, find out if necessary
- [x] generate ideas what might be needed to be mocked to which extend in relation to our pipeline
- [x] Suggest some "test style standards"
- [x] Suggest a structure for Test components 
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by grittaweisheit** [comment]
Wiki page: [https://github.com/bptlab/cepta/wiki/TestNG-Introduction](url)

**Comment by skydivin4ng3l** [comment]
I would like to see a bit more concrete mentioning of how to create events compared to datastream and how timestamp handling would work. 

Also correlation related testing would be interesting.
