### ISSUE TITLE
Detect Train staying in a station

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#232]
### As a

Train delay analyzer

### I want

to see when trains arrive in a station, stay there, and later depart.

### Because

this usually changes the delay a lot.

## Tasks
- [x] Find this in our data
- [x] Open Pull Request
- [x] Gain knowledge about different best practices

## Acceptance Criteria
- [x] Documented
- [x] Merged in master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
