### ISSUE TITLE
Website for CEPTA with information

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#233]
### As a
Non technical viewer (e.g. during final presentation)

### I want
to find out what the project was about.

## Prerequisites
None

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Basic website containing the most relevant information about the project

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
