### ISSUE TITLE
Integrate auth and user management

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#235]
### As a
End user

### I want
to be able to use the authentication service

## Prerequisites
None

## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team
- [ ] Add `auth` and `usermgmt` microservice into prod and dev docker deployment
- [ ] Connect services with the new frontend
 

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
