### ISSUE TITLE
Sum of delays in a station exceeds a threshold

### ISSUE THREAD

**Issue by ma-ro** [bptlab/cepta#237]
### I want
to see the sum of delays in a station and see if it exceeds a treshold

## Tasks
- [x] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Merged in master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
Im not sure wether implementing this on TrainDelayNotification is the best.
The TrainDelayNotifications are (afaik) the events we want to generate and send to the frontend,
maybe we should read through the liveTrains and aggregate the delays there so we can use them for creating better TrainDelayNotifications?
