### ISSUE TITLE
Integrate Notification Micro-Service

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#238]
### As a
User

### I want
to receive all notifications about my trains at anytime

### Because
I am not always logged in and able to receive the notifications over an open websocket

## Tasks
- [x] Open Pull Request
- [x] Subscription to correct Kafka queue
- [x] Connection to UserDB
- [x] Add redis
- [x] Save User Notifications in rabbitMQ when logged out 
- [ ] Send Notification to the users frontend over websocket when logged in 
- [ ] (Possible Addition: contact E-Mail Micro-Service to send notifications to the user)

## Acceptance Criteria
- [x] Documented
- [x] Merged in dev
- [ ] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Is there a way to see this working?

**Comment by leopetter** [comment]
RabbitMQ was not suitable for our use case so we are using Redis now
