### ISSUE TITLE
Arriving train without planned data Pattern

### ISSUE THREAD

**Issue by grittaweisheit** [bptlab/cepta#243]
Implent the pattern "train is arriving but apparently has no planned data"

## Tasks
- [x] Open Pull Request
- [x] Implement the pattern

## Acceptance Criteria
- [x] Documented
- [ ] Merged in master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by grittaweisheit** [comment]
This is already done with the LivePlannedCorrelationFunction, as it returns a tuple of live and planned. When there is no planned date, the second part of the tuple is empty.

**Comment by Quacck** [comment]
Looks good :) It'd be nice if we could expand this pattern to the other types of a train traveling (arriving, departing and driving-through)
