### ISSUE TITLE
Delay shift on future events

### ISSUE THREAD

**Issue by ma-ro** [bptlab/cepta#246]
## Tasks
- [ ] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Merged in master
- [ ] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Maybe we can use java's compareTo() in the compareProtoTimestamps, also we should keep language for comments consistent
