### ISSUE TITLE
Detect Station Arrival Delay Operator

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#247]
### I want
basicly a refactor of our main, but with tests

matched live and planned difference calcuation and sending of traindelaynotification

## Tasks
- [x] Open Pull Request
- [ ] Gain knowledge about different best practices
- [ ] Prepare a short presentation to share your insights with the Team

## Acceptance Criteria
- [x] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Nice :)
