### ISSUE TITLE
Filter Events in Frontend

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#249]
### As a

cepta user

### I want

to be able to filter events so i only see the events that interest me.
I should be able to get a high-level view, which for example would only include delays in certain stations, or a low-level-view which would help me understand why the delays occur.

Ideally, this would be a simple slider or a set of presets that lets me filter out events, scaling from high-level to low-level. But I would also be happy with a checkbox-style filter that lets me select each event i want to see.

### Because

my trusty team of developers is creating new patterns and events which might not always be interesting to the user and clutter the frontend.

It could also be used for debugging purposes.

## Tasks
- [ ] In the detailed view with the map, have an element that lets me adjust the filter
- [ ] ablity to hide these filters, so i can concentrate on the shown events
- [ ] _optional:_ these filters are saved to my user for the next session
- [ ] _optional:_ ability to filter groups of events (based on some kind of hierarchy?)

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
