### ISSUE TITLE
[2] Implement producer for Running Train Data events from dump

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#25]
### As a
Developer

### I want
simulated "real time" events of my trains

### Because
to simulate the occurrence of real time data events

## Tasks
- [ ] Pull Request open
- [ ] take spike of #15 as starting point build a producer for the "running Trains Data"

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
