### ISSUE TITLE
A way of evaluating our predictions

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#250]
### As a

developer

### I want

to check how well our predictions for delays turn out to be. 

### Because

we need to check whether our approaches work or not.

## Tasks
- [ ] Open Pull Request
- [ ] Discuss different ways to implement this
- [ ] a notification in our frontend showing a discrepancy

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green in Flink
- [ ] Code Review done
- [ ] Reviewed by PO
