### ISSUE TITLE
Documentation of our events

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#251]
### As a

developer

### I want

to have an overview of all the events we have.

I would like to have a class diagram (or similar) of our events.
 
### Because

we now keep creating patterns and events.
Having a documentation in which we can view our events and how they are created would give
us a better overview. We would then be able to better create new patterns and events.

## Tasks
- [ ] create a way to document our work on events and patterns 
- [ ] add what we have so far

## Acceptance Criteria
- [ ] Documented :D
- [ ] "Code Review" done
- [ ] Reviewed by PO

**Comment by Quacck** [comment]
This was covered in #273
