### ISSUE TITLE
Refactor Events

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#252]
### As a

developer

### I want

to refactor my events so they can share common attributes via inheritance or composition.

### Because

right now, many events share similar fields and will require similar functions.

We could, for example, also make better use of patterns' `.subtype` method or create streams with different kinds of events. As well as other benefits of avoiding code duplication.

## Tasks
- [ ] decide whether this is a good idea?
- [ ] look up different strategies to do this (maybe ask our academic advisors)
- [ ] implement :)

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and still green
- [ ] Code Review done
- [ ] Reviewed by PO
