### ISSUE TITLE
Integrate StaysInStation into Main

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#258]
see #254 

## Tasks
- [x] Open Pull Request
- [ ] share your insights with the Team
- [x] add staysInStation into main

## Acceptance Criteria
- [x] Documented
- [x] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Noice
