### ISSUE TITLE
[3] Implement DB for Planned Train Data filled via Events

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#26]
### As a
Train Planner

### I want
to submit / update my planned train Data to cepta

### Because
I want cepta to inform me about ETA changes of my trains in the future, based on correlated running train data events

### Prerequisite 
- [ ] #29 
- [ ] #33

## Tasks
- [x] Pull Request open
- [x] implement a DB which gets filled/updated by Flink as soon as Planned Train Data events "arrive" via Kafka
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
So as i reviewed the PR I did not see any usage of the Train Data, is the PR just the implementation of the capability to fill a database by events?
