### ISSUE TITLE
coding and testing guidelines

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#264]
### As a

developer

### I want

to have guidelines for writing code and testing.

### Because

we waste alot of time because we have a different 
understanding of what our code should look like.

## Tasks
- [ ] create a document where we can see those guidelines.
- [ ] share your insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
