### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#265]
### As a

developer

### I want

to have my project documentated.

### Because

we would save time and thus be more productive if all members can find the necessary information.
This would also save us time later when we have to document our project for our academic advisors and project partners.

## Tasks
- [x] Open Pull Request
- [x] Replayer
- [x] CLI Options for our project
- [x] GRPC calls from and to our microservices
- [ ] Patterns; which input they have and what meaning
- [ ] and wherever seems good :D

## Acceptance Criteria
- [x] Documented in READMEs
- [ ] Merged in dev
- [x] Code /Documentation Review done
- [ ] Reviewed by PO
