### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#266]
### As a
Developer

### I want
to run CI faster

### Because
this allows me to get feedback faster and not be tempted to merge untested branches

## Tasks
- [ ] Open Pull Request
- [ ] share your insights with the Team
- [ ] Convert travis config to github workflow
- [ ] Setup and configure custom GitHub Runner alongside travis
- [ ] Reconfigure GitHub CI checks

## Acceptance Criteria
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
