### ISSUE TITLE
[2] Implement Flink CEP Agents to correlate Planned with Running Train Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#27]
### As a
Train Planner

### I want
get information about the running status of my planned train, one specific

### Because
I want to know how my planned trains perform

## Prerequisite
- [ ] #34

## Tasks
- [ ] Pull Request open
- [x] Implement a filter for a specific train tis
- [x] display tupel of planned data and live train data
- [ ] receive live train data

## Acceptance Criteria
- [ ] Documented
- [x] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [x] Reviewed by PO
