### ISSUE TITLE
Pattern for delay predictions in red bull

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#277]
### As a
Developer

### I want
to start with a small scope for implementing and applying pattern

### Because
ist fundamental to start small and reach for the stars

## Tasks
- [ ] Open Pull Request
- [x] find a perfect use case in the DB datasets for the RedBull trains
- [ ] write a test runner for this use-case
- [ ] implement patterns against test runner
- [ ] ...

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
