### ISSUE TITLE
Manage transports in frontend

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#279]
### As a
Privileged user

### I want
to be able to assign myself transport IDs 

### Because
i want to receive notifications

## Tasks
- [ ] Open Pull Request
- [ ] share your insights with the Team
- [ ] Add archiver microservice for plan data archival
- [ ] Extend query service to allow querying available transports
- [ ] Extend usermgmt service to allow adding and removing of transport IDs to users

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
