### ISSUE TITLE
[2] Define Folder and overall Project Structure

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#28]
### As a
Developer

### I want
to know where i have to put what kind of components of the project and where to look for what kind of components

### Because
a clean, intuitive and ordered project structure increases overall productivity and quality

## Tasks
- [x] Pull Request open
- [x] Define Data Streaming topic naming conventions
- [x] decide how and reason why
- [x] how inject external components like readers / replayer / synfioo dump access (multiple git repos?)
- [x] inform yourself and discuss with the team what components might emerge  
- [x] Structure and organize project folder layout

## Acceptance Criteria
- [x] Documented in the wiki
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by Quacck** [comment]
Some good links i've found are [this one for kafka naming conventions](https://riccomini.name/how-paint-bike-shed-kafka-topic-naming-conventions?source=post_page-----1b7259790073----------------------) and [this one for structuring a package](http://dolszewski.com/java/project-package-organization/). We could also have a look at how e. g. flink handles its folders.
