### ISSUE TITLE
Generate mock events

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#282]
### As a
Developer [A] and potential user [B]

### I want to 
- [A] benchmark without the mongodb data lake bottleneck
- [B] see the platform performing without requiring access to confidential data 

## Tasks
- [ ] Open Pull Request
- [ ] share your insights with the Team
- [ ] Think about some realistic scenarios
- [ ] Provide good amount of configuration options to find the sweetspots later on
- [ ] Integrate in a user friendly startup procedure

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
