### ISSUE TITLE
test complete run of our system

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#284]
### As a

developer

### I want

to assure that a complete run of our system works. This would mean having events (re-) played into our system, then working on them on flink and finally showing the results in the frontend. 

### Because

creating this test this would help us find failing spots in our pipeline. It would also give us a better baseline of wether our system works or not.

## Tasks
- [ ] Open Pull Request
- [ ] create a full integration test that replays events, produces notifications and check whether they are shown in the front end.
 
## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
