### ISSUE TITLE
show events from flink in frontend

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#285]
### As a
cepta user

### I want
to see generated events in the frontend.

### Because
having delay predictions on real data would be nicer :) 

## Tasks
- [ ] Open Pull Request
- [x] all components should be runnable in our docker environment
- [x] send delay notifications from flink
- [x] connect from frontend to notification microservice
- [x] replayer can be started in the frontend
- [x] incoming events are shown in the live feed (or optionally, print them to the console)

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
