### ISSUE TITLE
[5] Spike DB for flink to correlate Data Events with DB Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#29]
### As a
Developer

### I want
to correlate Data events with other Event Data via a DB

### Because
I want to process the combined data in the future

## Tasks
- [x] Pull Request open
- [x] Review table API of Flink
- [x] spike a Database communication for data correlation within flink
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on spike branch
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
look into table api of flink

**Comment by grittaweisheit** [comment]
Documentation is in https://github.com/bptlab/cepta/wiki/Query-database-inside-flink (created by Vincent). We only added small findings we had during our exploration.

**Comment by skydivin4ng3l** [comment]
Please check all accomplished tasks.
