### ISSUE TITLE
Enrich Events with coordinates

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#290]
### As a
frontend developer

### I want
i want my incoming events to have coordiantes.

### Because
that way i can display them in the map view.

## Tasks
- [ ] Open Pull Request
- [ ] share your insights with the Team
- [ ] enrich notifications with coordinates
- [ ] create a map function that does that

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in dev
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
