### ISSUE TITLE
Prepare the final presentation

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#293]
### As a
project team

### We want
to show everyone what we did as our bachelor project.

## Tasks
- [ ] document details of the presentation (e.g. when? webcam? length? audience? screen-share?)
- [ ] summarize and research the topics from our outline, split the responsibilities
- [ ] create a neat presentation, link in comments
- [ ] get feedback from our advisors
- [ ] practice the presentation
- [ ] ... infront of the team!
