### ISSUE TITLE
create stable release on master until code freeze

### ISSUE THREAD

**Issue by Quacck** [bptlab/cepta#294]
### As an
academic advisor

### I want
to have the project in a stable state on the master.

### Because
that way the student team can finish the common work on the project and focus on their individual bachelorprojects.

## Tasks
- [ ] remove unnecessary code from project
- [ ] improve the readme (e.g. how to start the project)
- [ ] merge features from PRs in

## Acceptance Criteria
- [ ] Changelog adjusted
- [ ] Documented
- [ ] Merged in master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
