### ISSUE TITLE
[Not estimated yet] Analytic Architecture Spike 1

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#3]
### As a
Developer

### I want
to gain experience by implementing a small spike, based on  #2 with a more analytical approach.
Make predictions based on the correlated Data

### Because
I want to get a better understanding how features of Flink might be used to make such predictions.
What kind of predictions might be realizable?
What kind of Data is needed?
What might be limiting factors?
What are the Main Challenges?
What might change with a bigger scope?

## Tasks
- [ ] Pull Request open 
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Spike Branch
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
CEP Example might be expanded for this
