### ISSUE TITLE
[13] Spike some kind of Web Interface as a consumer for the flink output

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#30]
### As a
Train planer

### I want
to choose a train tis, about this tis i want to receive notifications 

### Because
I need a pretty overview how my planned train performs

## Tasks
- [ ] Pull Request open 
- [ ] implement start button for event replay of running data
- [ ] implement filter configuration for specific tis ( manual input of this in input field)
- [ ] explore drop down choice between all existing with autocomplete suggestions
- [ ] implement display of all events based on #27
- [x] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on spike branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
Closing as duplicate of #48.
