### ISSUE TITLE
[1] Setup Docker environment

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#31]
### As a
Dev

### I want
to be able to easily setup our dev environment

### Because
every dev should habe the same dev environment

## Tasks
- [x] Pull Request open 
- [x] document how to use.

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
please add a wiki page with at least a link to the deployment readMe, that we have all the documation in one place.

**Comment by leopetter** [comment]
Ist drin.

**Comment by skydivin4ng3l** [comment]
Seriously? Please add a bit more context to the wikipage, this is not the docker read me, but the readme how to deploy with docker or start cepta locally. While documenting always think about, who will read it, also in the future.

Also a beware stop postgresql DB locally if it is running, if you want to use the postgresql DB of the docker.

btw clicking on the links in the cepta cockpit always leads to unknown page / deadlink at least pg admin. pgadmin can only be started by using the shortcut of locally installed version, which then will connect to the docker DB if no other is running. Maybe include the status /usefulness of those links of the cockpit into the documentation.
