### ISSUE TITLE
[2] Implement Producer Planned train data events from dump

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#32]
### As a
Developer

### I want
to get the planned train data into our pipe line, e.g. kafka from our csv reader

### Because
we need to get the data into flink (internal DB in a simulated way)

## Tasks
- [x] Pull Request open 
- [ ] implement a producer for planned train data based on #15

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
This should be closed cause it is done within PR #58
