### ISSUE TITLE
[1] Implement flink consumer planned Train data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#33]
### As a
Developer

### I want
a flink consumer for produced planned train data

### Because
I want to process the data further like put them into a flink controlled DB for correlation 

## Prerequisite
- [ ] #32  

## Tasks
- [ ] Pull Request open
- [ ] implement a flink consumer for running train data based on #17 and #15
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
