### ISSUE TITLE
[Not estimated yet] Spike how to modularize cep agents in flink for our purposes

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#34]
### As a
Developer

### I don't want
to rewrite almost the same code every time
But I want to know if cep agents can be modularized for our purposes, at least as templates or otherwise if applicable. 

### Because
improve code quality, productivity and consistency 

## Tasks
- [ ] Pull Request open
- [ ] think about how flink cep agents could be modularized for our purposes
- [ ] think about use cases
- [ ] how could tests be simplified through modularization 
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on spike branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
