### ISSUE TITLE
[1] Implement flink consumer Running Train Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#35]
### As a
Developer

### I want
a flink consumer of the produced running train data events

### Because
I want to further process that data, like correlate or filter,...

## Prerequisite
- [ ] #25

## Tasks
- [ ] Pull Request open
- [ ] implement the flink consumer based on #17 and #15

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
