### ISSUE TITLE
[3] Docker dev environment works for everybody

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#36]
### As a
Dev

### I want
the provided docker dev env working

### Because
all should have the same environment

## Prerequisite
- [x] #31 

## Tasks
- [x] setup docker environment container
- [x] share docker container within the team
- [x] works at all Team Members workstations
- [x] ...windows
- [x] ...linux
- [x] ...macOS 
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on Master?
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
please check all accomplished tasks

**Comment by skydivin4ng3l** [comment]
Could please all verify that the docker dev setup is working and useful documented for them?
