### ISSUE TITLE
[5] Setup deployment of cepta on server

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#37]
### As a
Product Owner

### I want
to always see the current state of master branch on the "live" server 

### Because
I want to review all tasks on the live server

## Prerequisite
- [x] #36
- [x] #139 
- Some way of making automated releases

## Tasks
- [x] get access from the admins (asks Stephan/Sven for contact info)
- [x] receive the Introduction from admins
- [x] write docker compose file for production
- [ ] connect to vm and setup jenkins for own purpose
- [ ] setup cepta for deployment after each push to master

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
replaces #6

**Comment by leopetter** [comment]
We have access to the server via our VM and are able to configure our production deployment.
