### ISSUE TITLE
[2] Prepare physical Chart of Git-Hygine/Team-Rules/Project-Vision

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#38]
### As a
Team Member

### I want
to see our team reflected in the room

### Because
I want to feel at home keep track and be reminded of our rules and goals with a glace

## Tasks
- [ ] preview digital prettied up chart version to the team
- [ ] ...Git..
- [ ] ..Rules
- [ ] ..vision

## Acceptance Criteria
- [ ] Printed out and mounted on wall
- [ ] Team is Okay with it
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
tools Canva / piktochart

**Comment by skydivin4ng3l** [comment]
Concerning vision,...maybe also overall wishes of MW Chair.
- readable pretty code
- well designed expandable architecture
- build for extension by others in the future
- open source
