### ISSUE TITLE
[Not estimated yet] Explore time related Read from SQL DUMP File

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#4]
### As a
Developer

### I want
- to explore how we could use a SQL Dump file as a Mock for Event data generation.
- to replay the events in the correct order by timestamp or emulation of timestamps
- to maybe split the DATA into different producers if applicable to emulate different event Data sources which need to be subscribed by Kafka
- to be able to increase and decrease the rate of events and fast forward, rewind, select start time

### Because
Synfioo will provide a SQL Dump and we want to test our architecture with it. To Make it as realistic as possible we want to emulate a replay as closely as possible/necessary

## Tasks
- [ ] Pull Request open
- [ ] generate some basic test data for an test SQL dump
- [ ] implement replay of events as possible
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Spike Branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
