### ISSUE TITLE
[3] Docker dev configuration for all services

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#43]
### As a
Dev

### I want
a complete dev enviroment with access to all the necessary tools and commandline tools available with the docker environment

### Because
i need to be able to make use of the capabilities the tools within the docker environment e.g. kafka and flink have to offer.

## Prerequisite
- [x] #36

## Tasks
- [ ] Pull Request open 
- [x] Kafka tools available (create remove Topics start stop server....)
- [x] Flink tools available
- [x] Osiris is working in docker env
- [x] Proxy tool available

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
With #137 the dev docker env uses images created using bazel and osiris (rather it's fleet of microservices) is working fine.
