### ISSUE TITLE
[5] Implement CEP Agent detect difference between Plannend and Running Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#46]
### As a
Train Planner

### I want
to know when and how the plan differs reality and how the ETA changes

### Because
I need to know the current ETA

## Prerequisite
#27

## Tasks
- [ ] Pull Request open 
- [ ] filter and translate resulting correlation stream
- [ ] send new ETA (TIMESHIFT) Event (Key:Value - ERRID:delay)
- [x] think about how this ETA Event should look like, consider discussing with a colleage

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
