### ISSUE TITLE
[Not estimated yet] Analog Office Calander

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#47]
### As a
Team Member

### I want
an analog office calendar at the wall where i can write my leave and lookup important dates. 

### Because
I want to see all our important Dates at the office wall as a reminder

## Tasks
- [ ] get an analog year calendar
- [ ] 
- [ ] transcribe all fixed team dates available from outlook
- [ ] ask team to write down their leave time

## Acceptance Criteria
- [ ] Reviewed by TEAM
