### ISSUE TITLE
[13] Implement Prototype Web Interface

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#48]
### As a
Dev

### I want
a Web Interface for the Prototype Presentation

### Because
we need some kind of example demonstration

## Prerequisite
- [ ] #59

## Tasks
- [x] Pull Request open 
- [x] implemented a way to specify a Train ID (ERRID) to filter for (can be hard coded)
- [ ] Window with all incoming planned Train data (optional for Demo)
- [x] Window with all incoming running Train data (optional for Demo)
- [ ] Window with new ETAs for the remaining Train Stations on the timetable
- [ ] Window of ETA changing events with Reason
- [x] Button to restart the Replay Data process
- [x] Receive delay events in backend

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
