### ISSUE TITLE
[13] Implement Weather impact on Train Data ETA

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#49]
### As a
Train Planner

### I want
a prediction how the weather along the train trail might impact the ETA

### Because
weather might have a delaying factor

## Tasks
- [x] Write avro schema
- [x] implement producer
- [x] Add weather stream in Flink
- [x]  Correlate Train and weather events (location and coordinates)
- [x] send ETA altering Event (Timeshift) hardcoded delays per weather situation
- [x] Pull Request open 

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
