### ISSUE TITLE
[8] Research Deployment via Docker 

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#5]
### As a
Developer

### I want
to explore how deployment with docker and continuous Integration work 
with our architecture

### Because
- it would be good that the whole team has the knowledge how to do it
- we always want a presentation ready stable version
- the project partners might want to review our current state in the future
- the Product owner wants to experience the upcoming features on the test server with test data from the SQL Dump

## Tasks
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
follow up after pipeline is spiked

**Comment by skydivin4ng3l** [comment]
The link in this sentence does not work correctly?!

See the docker compose file documentation for more explanations.

**Comment by skydivin4ng3l** [comment]
It feels like the documentation is like a middlepart of something which misses context, for someone who does not know how to work with docker. maybe you could state a link for a good introduction page like the docker app page or something to have a good starting point to better understand the actual docker compose =)

With other words personally the documentation kinda helps to understand what the yaml file contains. Maybe this it the point of the documentation, so maybe we should in general state what the goal of all the wiki pages at the start.

It lacks a bit of how deployment works with docker. At least it misses the more general starting point links.

What is Docker Compose why Docker Compose and not just Docker.
Why we need multi container, don't we?

Maybe this documentation is a good follow up after the docker introduction for the team, we best talk about this =)

**Comment by skydivin4ng3l** [comment]
What is the Status of this?
