### ISSUE TITLE
[Not estimated yet] Receive delay event in backend 

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#50]
### As a
Train Planner

### I want
to receive the delay events flink is sending in our backend

### Because
to get notified as soon as a train delays and get the updated ETA on the timetable

## Prerequisite
#46

## Tasks
- [ ] Pull Request open 
- [ ] consumer of ETA events causing  a suitable update of the Web Interface

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
