### ISSUE TITLE
[13] Prototype Presentation Prep

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#51]
### As a
Team member

### I want
a demo script and prototype presentation slides

### Because
to make a good impression with our presentation and Demo of our prototype

## Tasks
- [x] Decide about content of Demo and Slides
- [x] Prep Slides
 

## Acceptance Criteria
- [x] on Google Drive
- [x] Reviewed by TEAM

**Comment by skydivin4ng3l** [comment]
presentation is in the google drive
