### ISSUE TITLE
[Not estimated yet] UML Class Diagram of Prototype

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#52]
### As a
Presenter

### I want
a UML Class Diagram of our prototype

### Because
it will be good to explain our architecture?

## Prerequisite
Prototype architecture kinda ready

## Tasks
- [ ] decide with team about tool to use
- [ ] UML class Diagram

## Acceptance Criteria
- [ ] on Google Drive
- [ ] Reviewed by TEAM

**Comment by skydivin4ng3l** [comment]
we don't need this
