### ISSUE TITLE
[1] Activity Diagram

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#53]
### As a
presenter

### I want
a BPMN diagram of the pipeline

### Because
i want to be able to better explain it

## Tasks
- [ ] decide with the team in which detail and what parts of the pipeline are suitable
- [ ] BPMN diagram of pipeline

## Acceptance Criteria
- [x] on Google Drive
- [x]  included in the presentation
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
There was an issue concerning UML and NOT BPMN.

Now finished and uploaded.
