### ISSUE TITLE
[Not estimated yet] How does local postgre influence docker setup

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#54]
### As a
Dev

### I want
to know how a local postgre works with the docker dev environments postgre

### Because
it is unclear how they influence each other and how it is supposed to work

## Tasks
- [ ] delete this and write the tasks down that are necessary to accomplish this user story

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are still green
- [ ] Code Review done
- [ ] Reviewed by PO
