### ISSUE TITLE
[2] Search for sample ERRID Data for Demo

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#56]
### As a
Presenter

### I want
a good example ERRID running data which has an delay, ideally delay and catchup

### Because
we want to show how our prototype works

## Tasks
- [x] search for a ERRID
- [x] ask synfioo
- [ ] state finding at prototype vision wiki page

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
Date_TrainNummers_ERRID

2019-08-02_43003_000039227032
2019-10-17_43521_000046321464
2019-09-10_43126-50206_000040622425
2019-10-04_43035_000044387523
2019-08-02_40040_000039202247
