### ISSUE TITLE
[13] Decompose into maven multi module project

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#58]
### As a
Developer

### I want
to be able to decompose functionality into dedicated modules and compile different jar targets for independent services.

### Because
This makes for better expandability and deployment strategies.

## Prerequisite
All open pull requests have been merged to master.

## Tasks
- [x] Pull Request open
- [x] Build all modules as well as individual modules
- [x] Share dependencies where possible 
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO

**Comment by romnn** [comment]
For documentation on the project structure see the [wiki](https://github.com/bptlab/cepta/wiki/WIP-Project-Structure).
