### ISSUE TITLE
[13] Implement prototype backend for the web interface

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#59]
### As a
Developer

### I want
to be able to gather the required data for the frontend presentation layer

### Because
it can then be further processed to provide valuable insights for the end user.

## Prerequisite
None

## Tasks
- [x] Pull Request open
- [x] Setup a simple spring boot java backend as a maven module
- [x] Add dependencies required for connecting to kafka and publish a websocket endpoint
- [x] Implement mock websocket communication
- [x] Optional: Use a proper message queue like RabbitMQ for websocket distribution
- [x] Optional: Implement JSON REST endpoint /test for testing grpc calls until the grpc proxy is set up 
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [ ] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
