### ISSUE TITLE
[20 / ?] Explore Deployment of a Spike via Docker on MW chairs server

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#6]
### As a
Product Owner

### I want
to review the future features on the newest Version on a Server 

### Because
- the PO don't want to accept only features running on one dedicated machine
- we always want a presentation ready stable version
- the project partners might want to review our current state in the future
- the Product owner wants to experience the upcoming features on the test server with test data from the SQL Dump

## Tasks
- [ ] take one of the spikes and deploy it
- [ ] test CI with Jenkins
- [ ] test CI with Travis
- [ ] present the running deployed spike on the server
- [ ] document pro & cons of Jenkins & Travis

## Acceptance Criteria
- [ ] Documented
- [ ] on Test Branch
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
