### ISSUE TITLE
[5] Refactor core into maven modules

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#60]
### As a
Developer

### I want
nice and clean dependencies and abstractions around the cepta architecture  

### Because
it avoids building towards a monolith and encourages code reuse.

## Prerequisite
- All open pull requests have been merged into master.
- Maven multi module setup

## Tasks
- [x] Pull Request open
- [x] Refactor by thinking about ownership and responsabilities
- [x] gain knowledge about different best practices
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
