### ISSUE TITLE
[1] Flink to frontend streaming

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#66]
### As a
Developer

### I want
a working pipeline for the Prototype Presentation

### Because
we need some kind of example demonstration

## Tasks
- [x] Publish correlated delay events in a kafka queue
- [x] Receive data from the kafka queue in the frontend
- [x] Publish received data from the backend to the frontend
- [x] Receive data in the Frontend

## Acceptance Criteria
- [ ] Documented
- [x] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
