### ISSUE TITLE
[1] Prototyp data visualisation Frontend

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#68]
### As a
Developer

### I want
a working delay event feed for the Prototype Presentation

### Because
we need some kind of example demonstration

## Tasks
- [x] Display incoming delay events in a table

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [ ] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
