### ISSUE TITLE
[3] Research how information about personal transport by train can be collected

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#7]
### As a
Planer of railbased cargo transportation

### I want
to get informed about expected delays of my cargo related to prioritized delayed personal transport.

### Because
these would increase the precision of ETA if delays of personal transports are an additional indicator 

## Tasks
- [x] gain knowledge about possible data sources
- [x] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.

**Comment by skydivin4ng3l** [comment]
split CI and Deployment

**Comment by leopetter** [comment]
We decided on leaving this data option off the table due to a lack of data sources and a very hard correlation between these tracks (ex. there are multiple track lanes between train connection)
