### ISSUE TITLE
[5] Dedicated external Data Source Server

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#74]
### As a
Developer

### I want
an external Database as a common Data Source

### Because
our laptops have only a small storage capacity

## Tasks
- [ ] Receive a external hard drive
- [ ] Setup the server
- [ ] Load the data

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by romnn** [comment]
Due to network firewall issues in our office this might need to be further delayed until we setup our own private network.
