### ISSUE TITLE
[Not estimated yet] Backend has TimeTable DB access

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#76]
### As a
Developer

### I want
to access the timetable from our backend

### Because
timetable train data is needed in frontend

## Prerequisite
#95 

## Tasks
- [ ] Pull Request open 
- [ ] create a new service
- [ ] open a connection to the database
- [ ] access timetable train data
- [ ] send data to the frontend 

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
