### ISSUE TITLE
[2] Package diagram about our system

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#78]
### As a
Developer

### I want
a Package Diagram of our system 

### Because
of a better overview of our interfaces and how the components communicate

## Tasks
- [x] create package diagram
- [x] share with others

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO

**Comment by grittaweisheit** [comment]
https://www.lucidchart.com/invitations/accept/c4e23b03-723d-42d3-90d7-b895edfd7fda
have fun :)
