### ISSUE TITLE
[3] Translate JavaScript to TypeScript

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#79]
### As a
Developer

### I want
to work with a typed language in the frontend

### Because
the software will be more robust and to enable IDEs to provide a richer environment for spotting common errors as you type the code.

## Tasks
- [ ] Pull Request open 
- [ ] type all Vue Components to support typecript
- [ ] type all the other files in Osiris to erase javascript completely

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by ma-ro** [comment]
How do we handle Props?
