### ISSUE TITLE
[Not estimated yet] CEP Flights Exercise with Flink: ETA

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#8]
### As a
Passenger of Lufthansa

### I want
- I want to see the ETA of my booked flight on my In-Flight-Entertainment system 
- based on current speed and distance to target airport

### Because
I want to take a nap when it takes longer than an hour ;)

## Tasks
- [ ] Pull Request open 
- [ ] Mock data Source or read file when applicable 
- [ ] subscribe to open skymap with kafka
- [ ] implement the feature with flink
- [ ] send events with the current ETA of the flights correlated with booking data on a output stream 

## Acceptance Criteria
- [ ] Documented
- [ ] on CEP exercise branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
