### ISSUE TITLE
[Not estimated yet] Frontend: Window with all incoming planned Train Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#81]
### As a
Train Planner

### I want
to see all planned timetable data for one specific train

### Because
i want to compare with my own eyes with the live data in the future

## Tasks
- [ ] Pull Request open 

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
