### ISSUE TITLE
[5] Frontend: Table with all incoming running Train Data

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#82]
### As a
User

### I want
so see all incoming live train data for one specific train similar to the timetable and possible delay causes with their reason

### Because
it is transparent for interpretation of the received data and I can optimise my production

## Tasks
- [ ] Pull Request open 
- [ ] receive data from the backend
- [ ] visualise data in a table 
- [ ] add a toggle for possible delay and cause
- [ ] filter, search entries

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
