### ISSUE TITLE
[3] Frontend: Table with all delay events with reason

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#83]
### As a
Train Planner

### I want
to see a reason for the delay event send for the train.

### Because
it is transparent for interpretation of the received data

## Tasks
- [ ] Pull Request open 
- [ ] Correlation works
- [ ] receive data from the backend
- [ ] visualise data in a table 

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
