### ISSUE TITLE
[1] Envoy Proxy

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#87]
### As a
Developer

### I want
a Proxy for the communication between the components

### Because
of CORS Problems and to generally erase a middle man in the communication Stream

## Tasks
- [x] Pull Request open 
- [x] Functioning Proxy

## Acceptance Criteria
- [x] Documented
- [x] on Master
- [x] Linter is okay
- [x] Tests are written and green
- [x] Code Review done
- [x] Reviewed by PO
