### ISSUE TITLE
[3] Cleanup unused code (Frontend)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#88]
### As a
Developer

### I want
a clean repository

### Because
unused code is distracting

## Tasks
- [x] Pull Request open 
- [x] Cleanup HTML
- [x] Cleanup CSS
- [x] Remove unused components (should be accessible later on)

## Acceptance Criteria
- [x] on Master
- [x] Linter is okay
- [x] Code Review done
- [x] Reviewed by PO
