### ISSUE TITLE
[5] Bachelorthesis topic discussion

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#89]
### As a
Student

### I want
to have a bachelor thesis that fits my needs

### Because
I can work on something that interests me

## Tasks
- [x] Discuss in the whole group
- [ ] E-mail to Stephan and Sven with all topics
- [ ] save date for discussion with Stephan and Sven 

## Acceptance Criteria
- [ ] Documented

**Comment by leopetter** [comment]
Further discussion will follow with Sven and Stephan
