### ISSUE TITLE
[Not estimated yet] CEP Flights Exercise with Flink: City Fly over

### ISSUE THREAD

**Issue by skydivin4ng3l** [bptlab/cepta#9]
### As a
Passenger of Lufthansa

### I want
to get notified when my flight is passing by a known city

### Because
My love for big cities is greater than my anxiety of heights that i only want to look out the window when there is a city to see

## Tasks
- [ ] Pull Request open 
- [ ] Mock city location data
- [ ] use Skymap and Booking stream from #8 to correlate with city
- [ ] inform all passengers of fight and booking about city fly over

## Acceptance Criteria
- [ ] Documented
- [ ] on  CEp excercise branch
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
BP-CEP-Praktikum folder in the google drive for more information and example implementation with Esper. Ask the Team Members with CEP-Modul experience to help if needed.
