### ISSUE TITLE
[Not estimated yet] Research other framework for our backend 

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#90]
### As a
Developer

### I want
a well-working system for our backend without any useless overhead

### Because
it saves a lot of time 

## Tasks
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO
