### ISSUE TITLE
[8] Research all possible reasons for a train delay

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#91]
### As a
User

### I want
see good approximation of all possible delays and their reasons

### Because
I need to plan with the delays in my 'just in time' production

## Tasks
- [ ] find meaningfull insights in the data
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [x] Documented
- [x] Reviewed by PO

**Comment by leopetter** [comment]
[Results of the research](https://docs.google.com/document/d/1r7sHt0TT_hDYIFggPOVLOMX32cu4NYeXPFkr2T6ddpM/edit?usp=sharing)
