### ISSUE TITLE
[5] Frontend: Visualise planned train data and their running delays

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#92]
### As a
User

### I want
to see the saved planned timetable train data and their occurring delays

### Because
I want a total overview off all my trains

## Prerequisite
#96 

## Tasks
- [x] Pull Request open 
- [ ] query the data and receive them via websocket
- [x] Visualise the received data in a table
 - [ ] add a toggle for possible delay and cause
 - [x] filter, search entries

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by skydivin4ng3l** [comment]
https://vuejsexamples.com/a-vue-component-of-dynamic-table/ this might be a more interesting table than the grid.

**Comment by skydivin4ng3l** [comment]
Toggle is still missing.
Query is kind of a draft but query microservice is still WIP
should we do frontend tests?

**Comment by leopetter** [comment]
Frontend test are not necessary yet. This is an other user story and we first have to analyse weither they are useful or not.
