### ISSUE TITLE
[4] Allow fine grained controls of the replayer from the frontend

### ISSUE THREAD

**Issue by romnn** [bptlab/cepta#93]
### As a
Developer and User

### I want
to be able to control the Speed, the data and  of replay, 

### Because
this allows for an improved usability

## Prerequisite
None

## Tasks
- [ ] Pull Request open 
- [x] provide visual feedback of what the replayer is currently doing
- [x] Allow start, stop, pause
- [x] Allow changing the data or the replayed ID
- [x] Allow changing between proportional or constant speed replay
- [x] Allow access to the replayer from all pages

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
With #137 fine grained replayer control has been implemented.
