### ISSUE TITLE
[2] Research available Libraries for our backend programming language

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#94]
### As a
Developer

### I want
all needed Libraries already implemented in our used programming language

### Because
I don't want to write them myself

## Tasks
- [ ] gain knowledge about different possible programming languages
- [ ] research for GO
- [ ] research for nodeJS
- [ ] research for others..?? (in case the ones above aren't working)

## Acceptance Criteria
- [ ] Documented
- [ ] Reviewed by PO

**Comment by romnn** [comment]
We will need the following libraries for sure:

Library | Available in Go | Available in nodeJS | Available in Rust
--------- | ----------------- | --------------------- | ------------------- |
SQL (Async)         | Yes | Yes | Yes 
gRPC / HTTP2        | Yes | Yes | Yes (under development grpc-rust) 
GraphQL         | Yes | Yes | Yes (ex. juniper)
JSON         | Yes | Yes | Yes
WebSockets         | Yes | Yes | Yes
AVRO??        | Yes | Yes | Yes
