### ISSUE TITLE
[13] Connect written microservices in one architecture

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#95]
### As a
Developer

### I want
to build the microservice architecture from the written services

### Because
I want a seemless transition from our existing backend to our new one

## Prerequisite
- #97 
- #96 

## Tasks
- [x] Structure microservices in an extensible and efficient manner
- [ ] Create (one?) Dockerfile for running microservices 
- [x] Integrate build system (e.g. bazel)
- [x] Implement common interfaces between the services (gRPC, GraphQL) and data schemas (protobuf)
- [x] Integrate services into docker compose and setup communication

## Acceptance Criteria
- [ ] Documented
- [ ] Linter is okay
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
I will be looking into using go as our primary choice for microservices. So far, the focus of research is about how to structure microservices inside our monorepo while still keeping a small footprint.

See [here](https://stackoverflow.com/questions/55442878/organize-local-code-in-packages-using-go-modules/57314494#57314494) for a discussion about module management.

**Comment by romnn** [comment]
Completed with merge of #137
