### ISSUE TITLE
[8] Go Microservice: Querying

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#96]
### As a
Developer

### I want
a communication between my all my services

## Tasks
- [ ] Pull Request open 
- [ ] write query service
- [ ] communicate with others about the usage

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
