### ISSUE TITLE
[8] Go Microservice: Notification Websocket

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#97]
### As a
User

### I want
to receive notifications of infos to my trains

### Because
I need updates for their arrival and these correlated updates have to be send from backend to frontend via websockets

## Tasks
- [x] connect kafka queue
- [x] read from queue and push to the frontend
- [x] create websocket connection for multiple clients 
- [x] send data to specific clients
- [x] Pull Request open 

## Acceptance Criteria
- [ ] Documented
- [x] on Master
- [x] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO
